image: gradle:8.6-jdk17 # Vérifie l'image utilisée

stages:
- build
- test
- pack
- publish

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  JAVA_HOME: "/opt/java/openjdk" # Assurez-vous que c'est la bonne valeur

before_script:
- echo "🔧 Initialisation de l'environnement..."
- chmod +x gradlew # S'assurer que Gradle Wrapper est exécutable
- java -version # Vérifier la version de Java

build:
  stage: build
  script:
  - ./gradlew build
  artifacts:
    paths:
    - build/libs/*.war
    expire_in: 1 week

test:
  stage: test
  script:
  - ./gradlew test
  allow_failure: false # Le pipeline échoue si les tests échouent

pack:
  stage: pack
  script:
  - ./gradlew war # Si c'est un projet WAR
  artifacts:
    paths:
    - build/libs/*.war
    expire_in: 1 week

publish:
  stage: publish
  script:
  - echo "Authentification pour GitLab Package Registry..."
  - echo "machine gitlab.com login ${CI_DEPLOY_USER} password ${CI_DEPLOY_PASSWORD}" > ~/.netrc
  - ./gradlew publish
  dependencies:
  - pack
  rules:
  - if: $CI_COMMIT_BRANCH == "main"
